name: Pull Request Workflow
on: [pull_request, workflow_dispatch]
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - name: Install libgtk-3-0
        run: sudo apt-get install -y libgtk-3-0
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Run tests
        run: ./gradlew test --no-daemon