name: Pull Request Workflow
on: [pull_request, workflow_dispatch]
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Set up Virtual Display (for Linux)
        run: |
          Xvfb :99 -screen 0 1920x1080x24 -nolisten unix &

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Run tests
        run: ./gradlew test --no-daemon